export const Android = 'Android';
export const iOS = 'iOS';
export const Linux = 'Linux';
export const MacOs = 'MacOS';
export const Unknown = 'Unknown';
export const Windows = 'Windows';
export const iOSPlatforms = ['iPhone', 'iPad', 'iPod'];
export const MacOsPlatforms = ['Macintosh', 'MacIntel', 'MacPPC', 'Mac68K'];
export const WindowsPlatforms = ['Win32', 'Win64', 'Windows', 'WinCE'];