export const AppName = 'n';
export const BrowserAvailableMemory = 'browser_available_memory';
export const BrowserUsedMemory = 'browser_used_memory';
export const BannerShowsCounter = 'counter_banner_showed';
export const BannerSourceUrl = 'source_url';
export const ClientHints = 'client_hints';
export const CustomUserId = 'custom_user_id';
export const CurrentDeviceTime = 'current_device_time';
export const DeeplinkParam = '_dl';
export const DeferredDeeplinkParam = '_ddl';
export const DocumentReferrer = 'document_referrer';
export const EventId = 'event_id';
export const EventName = 'n';
export const EventProductName = 'product_name';
export const Extra = 'e';
export const GlobalProperties = 'global_properties';
export const IsConversion = 'conversion_event';
export const IsFirstEvent = 'first';
export const IsFirstVisit = 'is_first_visit';
export const IsFirstPageVisitInSession = 'is_first_page_visit_in_session';
export const IsPageRefreshed = 'is_page_refreshed';
export const IsRevenueEvent = 'is_revenue_event';
export const IsSetMatchId = 'is_set_match_id';
export const Keyspace = 'k';
export const Lag = 'lag';
export const Locale = 'l';
export const MatchId = 'match_id';
export const OS = 'os';
export const ECID = 'ecid';
export const Owner = 'a';
export const PassthroughParam = '_p';
export const Platform = 'p';
export const PlatformWeb = 'Web';
export const PreviousSdid = 'prev_sdid';
export const ProductId = 'i';
export const RevenueAmount = 'r';
export const RevenueCurrency = 'pcc';
export const ScreenHeight = 'screen_height';
export const ScreenWidth = 'screen_width';
export const SdidPersistMode = 'sdid_persist_mode';
export const SdidPersistFailedReason = 'sdid_persist_failed_reason';
export const SdkVersion = 'sdk';
export const SessionId = 's';
export const SingularDeviceId = 'SDID';
export const SingularInstanceId = 'singular_instance_id';
export const StorageType = 'storage_type';
export const Timezone = 'timezone';
export const TouchpointTimestamp = 'touchpoint_timestamp';
export const UserAgent = 'device_user_agent';
export const UUID = 'u';
export const UUID_REGEX = '^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$';
export const WebParams = '_web_params';
export const WebUrl = 'web_url';
export const LastDismissed = 'last_dismissed';
export const BannerName = 'bn';
export const BannerID = 'baid';
export const Source = 'utm_source';

export const WebUrlMarketingParams = {
    "clid_params": ['clid='],
    "singular_p_params": [
        'pcnid=',
        'pcrnid=',
        "pcid=",
        "pcn=",
        "psc=",
        "pscid=",
        "pscn=",
        "pcrid=",
        "pcrn=",
        "ps=",
        "psid=",
        "psn=",
        "pshid=",
        "paffid=",
        "paffn=",
        "pcc=",
        "psrc=",
        "pmed="],
    "singular_wp_params": [
        "wpcid=",
        "wpcn=",
        "wpsc=",
        "wpscid=",
        "wpscn=",
        "wpcrid=",
        "wpcrn=",
        "wps=",
        "wpsid=",
        "wpsn=",
        "wpshid=",
        "wpaffid=",
        "wpaffn=",
        "wpkw=",
        "wpsrc=",
        "wpmed="],
    "utm_params": ['utm_.+='],
    "additional_params": ["kw=", "an=", "ud="],
};


